<a href="https://colab.research.google.com/github/eughappy/HomeWork/blob/linear_hw/linear_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# **1**

In [ ]:
a = np.arange(1,11, dtype = int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


# **2**

In [ ]:
matrix = np.zeros((3,3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# **3**

In [ ]:
rand_m1 = np.random.randint(1,11,(5, 5))
print(rand_m1)

[[10  4  1  8  1]
 [ 9  6  9  2  2]
 [ 6  5  2  9  1]
 [ 8  6  4  3  8]
 [ 1 10  5  6  5]]


# **4**

In [ ]:
rand_m2 = np.random.random_sample((4,4))
print(rand_m2)

[[0.75890043 0.93303042 0.18971056 0.2387415 ]
 [0.68645543 0.36644796 0.33077462 0.26040977]
 [0.98732047 0.57529954 0.66203737 0.89034603]
 [0.03248576 0.57102085 0.25504352 0.38711088]]


# **5**

In [ ]:
m1 = np.random.randint(1,11,(5, 5))
m2 = np.random.randint(1,11,(5, 5))
print("m1:\n",m1)
print("m2:\n",m2,"\n")
print("m1+m2:\n", m1+m2)
print("m1-m2:\n", m1-m2)
print("m1*m2:\n", m1*m2)

m1:
 [[ 2  7  9  8 10]
 [ 6  5  2  3  1]
 [ 2  9  4  1  2]
 [ 3  3  8  5 10]
 [ 2  7  9  2  5]]
m2:
 [[3 9 7 3 1]
 [3 3 7 2 8]
 [7 8 8 4 9]
 [9 7 1 3 2]
 [5 7 3 8 4]] 

m1+m2:
 [[ 5 16 16 11 11]
 [ 9  8  9  5  9]
 [ 9 17 12  5 11]
 [12 10  9  8 12]
 [ 7 14 12 10  9]]
m1-m2:
 [[-1 -2  2  5  9]
 [ 3  2 -5  1 -7]
 [-5  1 -4 -3 -7]
 [-6 -4  7  2  8]
 [-3  0  6 -6  1]]
m1*m2:
 [[ 6 63 63 24 10]
 [18 15 14  6  8]
 [14 72 32  4 18]
 [27 21  8 15 20]
 [10 49 27 16 20]]


# **6**

In [ ]:
v1 = np.linspace(1,7,7,dtype=int)
v2 = np.random.randint(1,11,7)
print(f"|v1: {v1}\n|v2: {v2}\n|v1*v2: {np.dot(v1,v2)}")

|v1: [1 2 3 4 5 6 7]
|v2: [2 9 6 8 5 1 4]
|v1*v2: 129


# **7**

In [ ]:
m1 = np.random.randint(1,11,(2,2))
m2 = np.random.randint(1,11,(2,3))
print("m1:\n", m1 , "\nm2:\n", m2, "\nm1*m2:\n",np.dot(m1,m2))

m1:
 [[3 5]
 [3 9]] 
m2:
 [[4 1 4]
 [2 4 6]] 
m1*m2:
 [[22 23 42]
 [30 39 66]]


# **8**

In [ ]:
m = np.random.randint(1,10,(3,3))
print("m:\n", m, "\nОбернена:\n", np.linalg.inv(m))

m:
 [[6 4 9]
 [4 1 5]
 [1 7 8]] 
Обернена:
 [[ 1.         -1.14814815 -0.40740741]
 [ 1.         -1.44444444 -0.22222222]
 [-1.          1.40740741  0.37037037]]


# **9**

In [ ]:
m = np.random.random_sample((4,4))
print("m:\n", m, "\nТранспонована:\n", m.T)

m:
 [[0.12409922 0.9803117  0.00918055 0.7359641 ]
 [0.98733689 0.94223848 0.48600361 0.69047166]
 [0.71021246 0.78295018 0.80421003 0.18859531]
 [0.67627484 0.52282413 0.23442841 0.3092219 ]] 
Транспонована:
 [[0.12409922 0.98733689 0.71021246 0.67627484]
 [0.9803117  0.94223848 0.78295018 0.52282413]
 [0.00918055 0.48600361 0.80421003 0.23442841]
 [0.7359641  0.69047166 0.18859531 0.3092219 ]]


# **10**

In [ ]:
m = np.random.randint(1,11,(3,4))
v = np.random.randint(1,11,4)
print("m:\n", m, "\nv:\n", v, "\nm*v:\n",np.dot(m,v))

m:
 [[10  2  7  9]
 [10  9 10  4]
 [10  9  3  3]] 
v:
 [2 7 2 4] 
m*v:
 [ 84 119 101]


# **11**

In [ ]:
m = np.random.random_sample((4,4))
v = np.random.random_sample(4)
print("m:\n", m, "\nv:\n", v, "\nm*v:\n",np.dot(m,v))

m:
 [[0.85192822 0.14992877 0.31697178 0.4038566 ]
 [0.88108388 0.41599913 0.48123856 0.56489635]
 [0.94841531 0.45102395 0.12171267 0.84964519]
 [0.71817446 0.94313163 0.9322711  0.15749047]] 
v:
 [0.59674004 0.75798947 0.68279187 0.44055497] 
m*v:
 [1.01637089 1.41855466 1.36524863 1.84937763]


# **12**

In [ ]:
m1 = np.random.randint(1,11,(2, 2))
m2 = np.random.randint(1,11,(2, 2))
print("m1:\n",m1)
print("m2:\n",m2,"\n")
print("m1*m2:\n", m1*m2)

m1:
 [[1 1]
 [4 6]]
m2:
 [[ 6 10]
 [ 6  6]] 

m1*m2:
 [[ 6 10]
 [24 36]]


# **13**

In [ ]:
m1 = np.random.randint(1,11,(2, 2))
m2 = np.random.randint(1,11,(2, 2))
print("m1:\n",m1)
print("m2:\n",m2,"\n")
print("Добуток:\n", np.dot(m1,m2))

m1:
 [[6 5]
 [6 2]]
m2:
 [[ 8  7]
 [ 4 10]] 

Добуток:
 [[68 92]
 [56 62]]


# **14**

In [ ]:
m = np.random.randint(1,101,(5, 5))
print("m:\n", m, "\nСума:\n", np.sum(m))

m:
 [[80 66 35 92 26]
 [93 10 86 56 83]
 [17 63 74 46  1]
 [89 95 95 97 57]
 [28 69 28 77 35]] 
Сума:
 1498


# **15**

In [ ]:
m1 = np.random.randint(1,11,(4, 4))
m2 = np.random.randint(1,11,(4, 4))
print("m1:\n",m1)
print("m2:\n",m2,"\n")
print("Різниця:\n", m1-m2)

m1:
 [[ 5 10  1  3]
 [10  7  9 10]
 [ 9  2  7  7]
 [ 8  6  4 10]]
m2:
 [[ 9  3  5  5]
 [ 7  8  5  5]
 [ 6  5  7  8]
 [ 6  7 10  8]] 

Різниця:
 [[-4  7 -4 -2]
 [ 3 -1  4  5]
 [ 3 -3  0 -1]
 [ 2 -1 -6  2]]


# **16**

In [ ]:
m = np.random.uniform(0,1,(3,3))
print("m:\n",m)
print("Vector:\n",np.reshape(m.sum(axis=1),(3,1)))

m:
 [[0.21002658 0.54468488 0.76911517]
 [0.25069523 0.28589569 0.85239509]
 [0.97500649 0.88485329 0.35950784]]
Vector:
 [[1.52382663]
 [1.38898601]
 [2.21936763]]


# **17**

In [ ]:
m = np.random.randint(-100,101,(3, 4))
m_m = m**2
print("m:\n", m, "\nm^2:\n", m_m)

m:
 [[ 65 -84  26 -48]
 [ 75  87 -56  -3]
 [  7 -95  43 -25]] 
m^2:
 [[4225 7056  676 2304]
 [5625 7569 3136    9]
 [  49 9025 1849  625]]


# **18**

In [ ]:
m = np.random.randint(0,101,(3, 4))
m_sqrt = np.sqrt(m)
print("m:\n", m, "\nm^2:\n", m_sqrt)

m:
 [[70 49 57 46]
 [75 28 31 16]
 [ 1 42 24  1]] 
m^2:
 [[8.36660027 7.         7.54983444 6.78232998]
 [8.66025404 5.29150262 5.56776436 4.        ]
 [1.         6.4807407  4.89897949 1.        ]]


# 2 **task**

# **1**

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# **2**

In [ ]:
m = np.random.randint(0,11,10)
print("Before resize:\n", m)
m.resize((2,5))
print("After resize:\n", m)

Before resize:
 [ 7 10  1  0  2  8 10  6  5  3]
After resize:
 [[ 7 10  1  0  2]
 [ 8 10  6  5  3]]


# **3**

In [ ]:
m1 = np.random.randint(0,11,(3,3))
m2 = np.random.randint(0,11,(3,3))
print("m1:\n", m1, "\nm2:\n", m2, "\nСкладені:\n", np.vstack((m1,m2)))

m1:
 [[9 2 0]
 [4 6 1]
 [4 9 4]] 
m2:
 [[9 8 6]
 [0 6 5]
 [7 3 0]] 
Складені:
 [[9 2 0]
 [4 6 1]
 [4 9 4]
 [9 8 6]
 [0 6 5]
 [7 3 0]]


# **4**

In [ ]:
a = np.array([1,2,3])
a1 = np.repeat(a,3)
a1 = np.hstack((a1,a))
a1 = np.hstack((a1,a))
a1 = np.hstack((a1,a))
print(a1)
#array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# **5**

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


# **6**

In [ ]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
indices = np.argsort(-a)[0:5]
print("a:\n",a,"\nindices:\n",indices)

a:
 [27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361] 
indices:
 [15 10  3  7 18]


# **7**

In [ ]:
f = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(f)
f_new = np.delete(f, np.where(np.isnan(f)))
print("Новий масив:", f_new)

[ 1.  2.  3. nan  5.  6.  7. nan]
Новий масив: [1. 2. 3. 5. 6. 7.]


# **8**

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
print("Евклідова відстань: ",np.linalg.norm(a - b))

Евклідова відстань:  6.708203932499369


# **9**

In [ ]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
count = np.cumsum(x==1)
idx = np.searchsorted(count, 5)
print("Індекс 5-го входження: ", idx)

Індекс 5-го входження:  8


# **10**

In [ ]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print("Масив:\n",a)
_, ix = np.unique(a, return_index=True)
a = np.full(a.shape,True)
a[ix] = False
print("Новий масив:\n",a)

Масив:
 [0 0 3 0 2 4 2 2 2 2]
Новий масив:
 [False  True False  True False False  True  True  True  True]
