<a href="https://colab.research.google.com/github/eughappy/HomeWork/blob/linear_hw/linear_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# **1**

In [ ]:
a = np.arange(1,11, dtype = int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


# **2**

In [ ]:
matrix = np.zeros((3,3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# **3**

In [ ]:
rand_m1 = np.random.randint(1,10,(5, 5))
print(rand_m1)

[[3 7 6 5 6]
 [8 4 1 8 9]
 [3 1 6 1 3]
 [2 7 1 4 8]
 [4 6 3 1 4]]


# **4**

In [ ]:
rand_m2 = np.random.random_sample((4,4))
print(rand_m2)

[[0.85689553 0.47298399 0.66327705 0.80572861]
 [0.2529805  0.07957344 0.73276061 0.96139748]
 [0.95380473 0.49049905 0.63219206 0.73299502]
 [0.9024095  0.16224692 0.40588132 0.41709074]]


# **5**

In [ ]:
m1 = np.random.randint(1,10,(5, 5))
m2 = np.random.randint(1,10,(5, 5))
print("m1:\n",m1)
print("m2:\n",m2,"\n")
print("m1+m2:\n", m1+m2)
print("m1-m2:\n", m1-m2)
print("m1*m2:\n", m1*m2)

m1:
 [[4 3 4 2 1]
 [7 6 3 1 1]
 [2 6 3 4 7]
 [2 5 4 2 5]
 [5 6 7 4 5]]
m2:
 [[4 8 8 3 5]
 [1 3 1 7 9]
 [2 6 7 5 7]
 [6 1 9 9 6]
 [4 3 9 8 2]] 

m1+m2:
 [[ 8 11 12  5  6]
 [ 8  9  4  8 10]
 [ 4 12 10  9 14]
 [ 8  6 13 11 11]
 [ 9  9 16 12  7]]
m1-m2:
 [[ 0 -5 -4 -1 -4]
 [ 6  3  2 -6 -8]
 [ 0  0 -4 -1  0]
 [-4  4 -5 -7 -1]
 [ 1  3 -2 -4  3]]
m1*m2:
 [[16 24 32  6  5]
 [ 7 18  3  7  9]
 [ 4 36 21 20 49]
 [12  5 36 18 30]
 [20 18 63 32 10]]


# **6**

In [ ]:
v1 = np.linspace(1,7,7,dtype=int)
v2 = np.random.randint(1,10,7)
print(f"|v1: {v1}\n|v2: {v2}\n|v1*v2: {np.dot(v1,v2)}")

|v1: [1 2 3 4 5 6 7]
|v2: [9 7 6 1 1 6 2]
|v1*v2: 100


# **7**

In [ ]:
m1 = np.random.randint(1,10,(2,2))
m2 = np.random.randint(1,10,(2,3))
print("m1:\n", m1 , "\nm2:\n", m2, "\nm1*m2:\n",np.dot(m1,m2))

m1:
 [[6 2]
 [2 1]] 
m2:
 [[4 7 8]
 [4 7 5]] 
m1*m2:
 [[32 56 58]
 [12 21 21]]


# **8**

In [ ]:
m = np.random.randint(1,10,(3,3))
print("m:\n", m, "\nОбернена:\n", np.linalg.inv(m))

m:
 [[6 7 5]
 [7 8 8]
 [4 1 3]] 
Обернена:
 [[ 0.33333333 -0.33333333  0.33333333]
 [ 0.22916667 -0.04166667 -0.27083333]
 [-0.52083333  0.45833333 -0.02083333]]


# **9**

In [ ]:
m = np.random.random_sample((4,4))
print("m:\n", m, "\nТранспонована:\n", m.T)

m:
 [[0.21097842 0.36052525 0.54937526 0.27183085]
 [0.46060162 0.69616156 0.5003559  0.71607099]
 [0.52595594 0.00139902 0.39470029 0.49216697]
 [0.40288033 0.3542983  0.50061432 0.44517663]] 
Транспонована:
 [[0.21097842 0.46060162 0.52595594 0.40288033]
 [0.36052525 0.69616156 0.00139902 0.3542983 ]
 [0.54937526 0.5003559  0.39470029 0.50061432]
 [0.27183085 0.71607099 0.49216697 0.44517663]]


# **10**

In [ ]:
m = np.random.randint(1,10,(3,4))
v = np.random.randint(1,10,4)
print("m:\n", m, "\nv:\n", v, "\nm*v:\n",np.dot(m,v))

m:
 [[3 1 6 4]
 [3 4 7 5]
 [2 4 2 5]] 
v:
 [9 9 3 3] 
m*v:
 [66 99 75]


# **11**

In [ ]:
m = np.random.random_sample((4,4))
v = np.random.random_sample(4)
print("m:\n", m, "\nv:\n", v, "\nm*v:\n",np.dot(m,v))

m:
 [[0.52803522 0.99215804 0.39503593 0.33559644]
 [0.80545054 0.75434899 0.31306644 0.63403668]
 [0.54040458 0.29679375 0.1107879  0.3126403 ]
 [0.45697913 0.65894007 0.25425752 0.64110126]] 
v:
 [0.20012361 0.65762481 0.77828922 0.7795984 ] 
m*v:
 [1.3272227  1.3952185  0.63328555 1.22247505]


# **12**

In [ ]:
m1 = np.random.randint(1,10,(2, 2))
m2 = np.random.randint(1,10,(2, 2))
print("m1:\n",m1)
print("m2:\n",m2,"\n")
print("m1*m2:\n", m1*m2)

m1:
 [[7 7]
 [6 7]]
m2:
 [[5 8]
 [4 3]] 

m1*m2:
 [[35 56]
 [24 21]]


# **13**

In [ ]:
m1 = np.random.randint(1,10,(2, 2))
m2 = np.random.randint(1,10,(2, 2))
print("m1:\n",m1)
print("m2:\n",m2,"\n")
print("Добуток:\n", np.dot(m1,m2))

m1:
 [[5 3]
 [5 4]]
m2:
 [[8 1]
 [1 6]] 

Добуток:
 [[43 23]
 [44 29]]


# **14**

In [ ]:
m = np.random.randint(1,100,(5, 5))
print("m:\n", m, "\nСума:\n", np.sum(m))

m:
 [[61  4 49 53 44]
 [37  6 72 39 87]
 [95 99 43 85 96]
 [77 34 59 43 23]
 [ 1 56 99 20 54]] 
Сума:
 1336


# **15**

In [ ]:
m1 = np.random.randint(1,10,(4, 4))
m2 = np.random.randint(1,10,(4, 4))
print("m1:\n",m1)
print("m2:\n",m2,"\n")
print("Різниця:\n", m1-m2)

m1:
 [[8 8 1 3]
 [4 3 6 9]
 [2 1 8 7]
 [3 1 9 3]]
m2:
 [[6 2 9 2]
 [6 5 3 9]
 [4 6 1 4]
 [7 4 5 8]] 

Різниця:
 [[ 2  6 -8  1]
 [-2 -2  3  0]
 [-2 -5  7  3]
 [-4 -3  4 -5]]


# **16**

In [ ]:
m = np.random.uniform(0,1,(3,3))
print(m)
print(m.sum(axis=1))

[[0.60380454 0.10514769 0.38194344]
 [0.03647606 0.89041156 0.98092086]
 [0.05994199 0.89054594 0.5769015 ]]
[1.09089567 1.90780848 1.52738943]


# **17**

In [ ]:
m = np.random.randint(-100,100,(3, 4))
m_m = m**2
print("m:\n", m, "\nm^2:\n", m_m)

m:
 [[ 41   0 -96  -9]
 [ 87 -33  35 -51]
 [ 75  93 -39 -86]] 
m^2:
 [[1681    0 9216   81]
 [7569 1089 1225 2601]
 [5625 8649 1521 7396]]


# **18**

In [ ]:
m = np.random.randint(0,100,(3, 4))
m_sqrt = np.sqrt(m)
print("m:\n", m, "\nm^2:\n", m_sqrt)

m:
 [[41  9 47 85]
 [43 63 16 94]
 [74 74 56 37]] 
m^2:
 [[6.40312424 3.         6.8556546  9.21954446]
 [6.55743852 7.93725393 4.         9.69535971]
 [8.60232527 8.60232527 7.48331477 6.08276253]]


# 2 **task**

# **1**

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# **2**

In [ ]:
m = np.random.randint(0,10,10)
print("Before resize:\n", m)
m.resize((2,5))
print("After resize:\n", m)

Before resize:
 [1 0 8 4 0 9 6 2 4 1]
After resize:
 [[1 0 8 4 0]
 [9 6 2 4 1]]


# **3**

In [ ]:
m1 = np.random.randint(0,10,(3,3))
m2 = np.random.randint(0,10,(3,3))
print("m1:\n", m1, "\nm2:\n", m2, "\nСкладені:\n", np.vstack((m1,m2)))

m1:
 [[2 5 8]
 [8 5 0]
 [1 6 7]] 
m2:
 [[4 1 7]
 [7 9 6]
 [4 7 3]] 
Складені:
 [[2 5 8]
 [8 5 0]
 [1 6 7]
 [4 1 7]
 [7 9 6]
 [4 7 3]]


# **4**

In [ ]:
a = np.array([1,2,3])
a1 = np.repeat(a,3)
a1 = np.hstack((a1,a))
a1 = np.hstack((a1,a))
print(a1)
#array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3]


# **5**

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


# **6**

In [ ]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
indices = np.argsort(-a)[0:5]
print("a:\n",a,"\nindices:\n",indices)

a:
 [27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361] 
indices:
 [15 10  3  7 18]


# **7**

In [ ]:
f = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(f)
f_new = np.delete(f, np.where(np.isnan(f)))
print("Новий масив:", f_new)

[ 1.  2.  3. nan  5.  6.  7. nan]
Новий масив: [1. 2. 3. 5. 6. 7.]


# **8**

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
print("Евклідова відстань: ",np.linalg.norm(a - b))

Евклідова відстань:  6.708203932499369


# **9**

In [ ]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
count = np.cumsum(x==1)
idx = np.searchsorted(count, 5)
print("Індекс 5-го входження: ", idx)

Індекс 5-го входження:  8


# **10**

In [ ]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print("Масив:\n",a)
_, ix = np.unique(a, return_index=True)
a = np.full(a.shape,True)
a[ix] = False
print("Новий масив:\n",a)

Масив:
 [0 0 3 0 2 4 2 2 2 2]
Новий масив:
 [False  True False  True False False  True  True  True  True]
